rules:
  body-full-stop:
    - 1
    - never
    - '.'

  body-leading-blank:
    - 1
    - always

  body-max-line-length:
    - 2
    - always
    - 80

  footer-leading-blank:
    - 1
    - always

  header-trim:
    - 2
    - always

  scope-case:
    - 2
    - always
    - lower-case

  subject-case:
    - 2
    - always
    - lower-case

  subject-empty:
    - 2
    - never

  subject-full-stop:
    - 2
    - never
    - '.'

  subject-max-length:
    - 2
    - always
    - 80

  type-case:
    - 2
    - always
    - lower-case

  type-empty:
    - 2
    - never

  type-enum:
    - 2
    - always
    - 
      - chore
      - ci
      - docs
      - feat
      - fix
      - perf
      - refactor
      - revert
      - style
      - test
      - WIP

